apiVersion: v1
kind: Service
metadata:
  name: cb-conversation
  labels:
    name: cb-conversation
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    role: cb-conversation
