apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cb-conversation
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: cb-conversation
        name: cb-conversation
    spec:
      containers:
      - image: 539277938309.dkr.ecr.us-west-2.amazonaws.com/cb-conversation:latest
        imagePullPolicy: Always
        name: cb-conversation
        env:
        - name  : appSecret
          value : "ec1c61500733d6998fde22261f73c181"
        - name  : pageAccessToken
          value : "EAAEnsPAELUMBADgSLdVm8jxd9krQqtjxrfn0VpY8Upa0KqBLLAq3CRTQjYUa4DZCTKDbu9ZCGMQj3TDWw2vUKQ9AxSZAlLIXwlYzWtoTSbAGawA4hka9eWsqhomosleZBTWeiJ8Si6B8fO667pSYGpROfRLcgVev5TlwnHtFUql1NGc1DXX1zoHFeaJUZC14ZD"
        - name  : validationToken
          value : "hellochatbrick"
        - name  : serverURL
          value : "https://chatbrick.herokuapp.com"
        ports:
        - containerPort: 3000